language: node_js
node_js: 8

before_script:
  - yarn global add greenkeeper-lockfile@1
  - greenkeeper-lockfile-update
  - yarn prepare-env

script:
  - yarn build
  - (cd functions && yarn && yarn build)
  - yarn check-size

after_script:
  - greenkeeper-lockfile-upload

deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "z9aBocF0dHE7/PvNHAsQ1tc6bDNbJX2ERkXP6g9IEQTWGaI9iHV7HxFQSBynoWaVZJjOSnSzPRKWbXZlzKKJ8NxR3KdkNT1ETP06FyanChN0JFxv1SLvsjuKuVlUdV9NzJ6WscQ7UbjCeJtszfJwN0iLHl8+pAWc/yaarEOQx5OfwIMTMpNVho4eH+sHx0BovcWDO8IHPZ6iSPEjrJrP4otlklG7yMuv0DeB2+f10eYH0WN5IX6fq4CFPM8uu6J0ZHKN0QYaiV1uF9dnL2YORuyYY1mUjnv8ZwjCzZmPBH480OzTxJC2IIfO/+cQsdB6A4v5wfz72+UuJIoZQNNYLI6KS1JCIeAojGBT3qubIJEE5Q49l8ES0GJA8SZB9npRtmPDE68t96rKGVj/ZLbK3cNgYP/G+Sdge5GI51WxItiHaGbah2vGtwuxBt42tJfb1AzxK5zb9X5f5HBi1y1FZLpEJvm88LUn7lEG4D7CiOuLP1mgEFh2FrboJK0yzWD+5wfaVV2PEHdH5CnvYA3S2g+1uAVYnvcKU6Nngfxk1k8K29DbJk1CA280uN4KsSA5HaAZ3KrTq6/IeVQoMfTRBhW0JXQ1xANrl5e0I3p5LuNFz6tFvDdf2nMDIwPLfo8LqY3s4aMA30dYJWjMj0yTy5gMrGHRjlf0XwtiUYeCiVc="
    project: "festify-dev"
    on:
      branch: develop
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "z9aBocF0dHE7/PvNHAsQ1tc6bDNbJX2ERkXP6g9IEQTWGaI9iHV7HxFQSBynoWaVZJjOSnSzPRKWbXZlzKKJ8NxR3KdkNT1ETP06FyanChN0JFxv1SLvsjuKuVlUdV9NzJ6WscQ7UbjCeJtszfJwN0iLHl8+pAWc/yaarEOQx5OfwIMTMpNVho4eH+sHx0BovcWDO8IHPZ6iSPEjrJrP4otlklG7yMuv0DeB2+f10eYH0WN5IX6fq4CFPM8uu6J0ZHKN0QYaiV1uF9dnL2YORuyYY1mUjnv8ZwjCzZmPBH480OzTxJC2IIfO/+cQsdB6A4v5wfz72+UuJIoZQNNYLI6KS1JCIeAojGBT3qubIJEE5Q49l8ES0GJA8SZB9npRtmPDE68t96rKGVj/ZLbK3cNgYP/G+Sdge5GI51WxItiHaGbah2vGtwuxBt42tJfb1AzxK5zb9X5f5HBi1y1FZLpEJvm88LUn7lEG4D7CiOuLP1mgEFh2FrboJK0yzWD+5wfaVV2PEHdH5CnvYA3S2g+1uAVYnvcKU6Nngfxk1k8K29DbJk1CA280uN4KsSA5HaAZ3KrTq6/IeVQoMfTRBhW0JXQ1xANrl5e0I3p5LuNFz6tFvDdf2nMDIwPLfo8LqY3s4aMA30dYJWjMj0yTy5gMrGHRjlf0XwtiUYeCiVc="
    project: "festify-79b08"
    on:
      branch: master

notifications:
  email: false
  slack:
    rooms:
      - secure: CB5ldw1lb5UhwTSikqyXQsfqTzfAAeoZ3sfrt5P4DTkP+FuUcAaj7n7sHwouuRdwmDrG7dcIHNywmvnVEmGFXwlmSy3Vcx/5hDtAfAm0YvUt1MUDm4NBRgOMqrSs8E75aZtAKlfV7eW1hTyS6idEH9CPJIgrd9ImG1SeBgz7ZmWdb5sZWg0OgUaWUeUerydhrsDQsuR5B721dvea249Y38FOhvGybTA8YDTViMEghuTOCKmZ/0Qaw1XavnbR/dxgVp4kxWJ6bG/vOHT0aB3Y17hckg97eGztHqjgBeF6Z6dn+Kt1rHW5trgjskmCCSfZiijRs4L1J7rGCcjAxc33BubMHOkXep59MM9gT78XCZadZkrQU2DFCq5icZPKaE4GLDFmR75CHIAh1jnr+IfQAzGILUs2LWzfabhmsy6m5QMDKNZJm5txN5X/cuZT2MDchC0BY0OElOVY6CBIpV5EJSl5XOcYGoTYXkdvqh1J7WnJmrAmlWwxQjLX+wpR1dutSo9kxfas9rB3zFCdFZ8Sj2aQj9kG5HLC9A7anj8EFs+ricHU/iprL+mrd8pFBWPsupVN6YE+xGAKFAoU0FZbuKLOfo1Et9coZwkchSTAWfJFhyJC54VOtquOtQ3Lhx8lmw3dfvGiXhQ+aetGO03c+e11XvgZpi2Aj9QOyxXYs8U=
    template:
      - "<%{build_url}|#%{build_number}> %{result}: <%{compare_url}|[%{repository_name}:%{branch}]> by %{author} (in %{duration})"
